export const SET_GUEST_CART_DATA = 'SET_GUEST_CART_DATA';
export const CART_DATA_REQUESTED = 'CART_DATA_REQUESTED';
export const CART_DATA_SUCCESS = 'CART_DATA_SUCCESS';
export const CART_DATA_FAIL = 'CART_DATA_FAIL';

export const REQUEST_ADD_TO_CART = 'REQUEST_ADD_TO_CART';
export const ADD_TO_CART_SUCCESS = 'ADD_TO_CART_SUCCESS';
export const ADD_TO_CART_FAIL = 'ADD_TO_CART_FAIL'; // this to add cart data in userData
export const REQUEST_REMOVE_FROM_CART = 'REQUEST_REMOVE_FROM_CART';
export const REMOVE_FROM_CART_SUCCESS = 'REMOVE_FROM_CART_SUCCESS';
export const REMOVE_FROM_CART_FAIL = 'REMOVE_FROM_CART_FAIL';
