export const PLACE_ODER_REQUEST = 'PLACE_ODER_REQUEST';
export const PLACE_ODER_SUCCESS = 'PLACE_ODER_SUCCESS';
export const PLACE_ODER_FAIL = 'PLACE_ODER_FAIL';

export const SET_ODER_PLACED_TO_INIT = 'SET_ODER_PLACED_TO_INIT';

export const REMOVE_FROM_CHECKOUT = 'REMOVE_FROM_CHECKOUT';
export const SET_CHECKOUT_COURSES = 'SET_CHECKOUT_COURSES';
export const REMOVE_CHECKOUT_COURSES = 'REMOVE_CHECKOUT_COURSES';
